---
- name: "Configure Azure Agent"
  become_user: "{{ username }}"
  azure_devops:
    action: install
    agent_name: "{{ agent_name }}"
    orgnization_url: "{{ orgnization_url }}"
    agent_token: "{{ agent_token }}"
    agent_pool_name: "{{ agent_pool_name }}"
    agent_deployment_group_name: "{{ agent_deployment_group_name }}"
    agent_deployment_group_project_name: "{{ agent_deployment_group_project_name }}"
  ignore_errors: true
  tags: azuredevops
